package org.cwgy.stock.core.model;

import java.util.Date;

public class StockModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.stock_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private String stockCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.international_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private String internationalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.stock_name
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private String stockName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.issue_date
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private Date issueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.market_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private String marketCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.securities_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private String securitiesCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.industry_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private String industryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.cfi_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private String cfiCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.is_enable
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private Integer isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.create_datetime
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock.update_datetime
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.stock_code
     *
     * @return the value of public.t_stock.stock_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.stock_code
     *
     * @param stockCode the value for public.t_stock.stock_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.international_code
     *
     * @return the value of public.t_stock.international_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public String getInternationalCode() {
        return internationalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.international_code
     *
     * @param internationalCode the value for public.t_stock.international_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setInternationalCode(String internationalCode) {
        this.internationalCode = internationalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.stock_name
     *
     * @return the value of public.t_stock.stock_name
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.stock_name
     *
     * @param stockName the value for public.t_stock.stock_name
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.issue_date
     *
     * @return the value of public.t_stock.issue_date
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public Date getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.issue_date
     *
     * @param issueDate the value for public.t_stock.issue_date
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.market_code
     *
     * @return the value of public.t_stock.market_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public String getMarketCode() {
        return marketCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.market_code
     *
     * @param marketCode the value for public.t_stock.market_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setMarketCode(String marketCode) {
        this.marketCode = marketCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.securities_code
     *
     * @return the value of public.t_stock.securities_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public String getSecuritiesCode() {
        return securitiesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.securities_code
     *
     * @param securitiesCode the value for public.t_stock.securities_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setSecuritiesCode(String securitiesCode) {
        this.securitiesCode = securitiesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.industry_code
     *
     * @return the value of public.t_stock.industry_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.industry_code
     *
     * @param industryCode the value for public.t_stock.industry_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setIndustryCode(String industryCode) {
        this.industryCode = industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.cfi_code
     *
     * @return the value of public.t_stock.cfi_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public String getCfiCode() {
        return cfiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.cfi_code
     *
     * @param cfiCode the value for public.t_stock.cfi_code
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setCfiCode(String cfiCode) {
        this.cfiCode = cfiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.is_enable
     *
     * @return the value of public.t_stock.is_enable
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.is_enable
     *
     * @param isEnable the value for public.t_stock.is_enable
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.create_datetime
     *
     * @return the value of public.t_stock.create_datetime
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.create_datetime
     *
     * @param createDatetime the value for public.t_stock.create_datetime
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock.update_datetime
     *
     * @return the value of public.t_stock.update_datetime
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock.update_datetime
     *
     * @param updateDatetime the value for public.t_stock.update_datetime
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}