package org.cwgy.stock.core.Mapper;

import java.util.Date;

public class TStockMarket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock_market.market_code
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    private String marketCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock_market.market_name
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    private String marketName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock_market.create_datetime
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.t_stock_market.update_datetime
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock_market.market_code
     *
     * @return the value of public.t_stock_market.market_code
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    public String getMarketCode() {
        return marketCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock_market.market_code
     *
     * @param marketCode the value for public.t_stock_market.market_code
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    public void setMarketCode(String marketCode) {
        this.marketCode = marketCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock_market.market_name
     *
     * @return the value of public.t_stock_market.market_name
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    public String getMarketName() {
        return marketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock_market.market_name
     *
     * @param marketName the value for public.t_stock_market.market_name
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    public void setMarketName(String marketName) {
        this.marketName = marketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock_market.create_datetime
     *
     * @return the value of public.t_stock_market.create_datetime
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock_market.create_datetime
     *
     * @param createDatetime the value for public.t_stock_market.create_datetime
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.t_stock_market.update_datetime
     *
     * @return the value of public.t_stock_market.update_datetime
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.t_stock_market.update_datetime
     *
     * @param updateDatetime the value for public.t_stock_market.update_datetime
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}