package org.cwgy.stock.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cwgy.stock.core.model.StockModel;
import org.cwgy.stock.core.model.StockModelExample;

public interface StockDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    long countByExample(StockModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int deleteByExample(StockModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int deleteByPrimaryKey(@Param("stockCode") String stockCode, @Param("internationalCode") String internationalCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int insert(StockModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int insertSelective(StockModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    List<StockModel> selectByExample(StockModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    StockModel selectByPrimaryKey(@Param("stockCode") String stockCode, @Param("internationalCode") String internationalCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") StockModel record, @Param("example") StockModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int updateByExample(@Param("record") StockModel record, @Param("example") StockModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int updateByPrimaryKeySelective(StockModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int updateByPrimaryKey(StockModel record);
}