package org.cwgy.stock.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cwgy.stock.core.model.StockMarketModel;
import org.cwgy.stock.core.model.StockMarketModelExample;

public interface StockMarketDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    long countByExample(StockMarketModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int deleteByExample(StockMarketModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int deleteByPrimaryKey(String marketCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int insert(StockMarketModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int insertSelective(StockMarketModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    List<StockMarketModel> selectByExample(StockMarketModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    StockMarketModel selectByPrimaryKey(String marketCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") StockMarketModel record, @Param("example") StockMarketModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int updateByExample(@Param("record") StockMarketModel record, @Param("example") StockMarketModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int updateByPrimaryKeySelective(StockMarketModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Fri Oct 02 18:57:41 CST 2020
     */
    int updateByPrimaryKey(StockMarketModel record);
}