package org.cwgy.stock.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cwgy.stock.core.Mapper.TStockMarket;
import org.cwgy.stock.core.Mapper.TStockMarketExample;

public interface TStockMarketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    long countByExample(TStockMarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int deleteByExample(TStockMarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int deleteByPrimaryKey(String marketCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int insert(TStockMarket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int insertSelective(TStockMarket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    List<TStockMarket> selectByExample(TStockMarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    TStockMarket selectByPrimaryKey(String marketCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") TStockMarket record, @Param("example") TStockMarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int updateByExample(@Param("record") TStockMarket record, @Param("example") TStockMarketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int updateByPrimaryKeySelective(TStockMarket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock_market
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int updateByPrimaryKey(TStockMarket record);
}