package org.cwgy.stock.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.cwgy.stock.core.Mapper.TStock;
import org.cwgy.stock.core.Mapper.TStockExample;

public interface TStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    long countByExample(TStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int deleteByExample(TStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int deleteByPrimaryKey(@Param("stockCode") String stockCode, @Param("internationalCode") String internationalCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int insert(TStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int insertSelective(TStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    List<TStock> selectByExample(TStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    TStock selectByPrimaryKey(@Param("stockCode") String stockCode, @Param("internationalCode") String internationalCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") TStock record, @Param("example") TStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int updateByExample(@Param("record") TStock record, @Param("example") TStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int updateByPrimaryKeySelective(TStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.t_stock
     *
     * @mbg.generated Wed Jul 15 12:19:10 CST 2020
     */
    int updateByPrimaryKey(TStock record);
}